export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "surface-container-highest": "#e5e2da",
            "primary-fixed-dim": "#ffb596",
            "inverse-on-surface": "#f4f1e8",
            "on-secondary-fixed-variant": "#5d4200",
            "on-tertiary-fixed": "#1b1c1c",
            "tertiary": "#4f4f4f",
            "background": "#fcf9f0",
            "on-tertiary-fixed-variant": "#474747",
            "on-surface": "#1c1c17",
            "on-error-container": "#93000a",
            "on-primary-fixed-variant": "#76320f",
            "secondary-fixed": "#ffdea6",
            "on-error": "#ffffff",
            "primary": "#823b18",
            "on-secondary-fixed": "#271900",
            "on-surface-variant": "#54433c",
            "surface-variant": "#e5e2da",
            "on-primary": "#ffffff",
            "on-primary-container": "#ffe1d6",
            "secondary-container": "#fdc34d",
            "inverse-surface": "#31312b",
            "on-background": "#1c1c17",
            "primary-fixed": "#ffdbcd",
            "tertiary-container": "#686767",
            "inverse-primary": "#ffb596",
            "surface-dim": "#dddad1",
            "tertiary-fixed": "#e4e2e1",
            "on-secondary": "#ffffff",
            "surface-tint": "#944925",
            "surface": "#fcf9f0",
            "on-tertiary-container": "#e9e6e6",
            "on-secondary-container": "#715000",
            "outline": "#87736b",
            "surface-container": "#f1eee5",
            "primary-container": "#a0522d",
            "surface-container-low": "#f6f3ea",
            "error-container": "#ffdad6",
            "secondary-fixed-dim": "#f7bd48",
            "tertiary-fixed-dim": "#c8c6c6",
            "on-tertiary": "#ffffff",
            "on-primary-fixed": "#360f00",
            "secondary": "#7b5800",
            "surface-container-high": "#ebe8df",
            "surface-container-lowest": "#ffffff",
            "error": "#ba1a1a",
            "outline-variant": "#dac1b8",
            "surface-bright": "#fcf9f0"
        },
        "borderRadius": {
            "DEFAULT": "0px",
            "lg": "0px",
            "xl": "0px",
            "full": "0px"
        },
        "fontFamily": {
            "headline": ["Noto Serif", "serif"],
            "body": ["Public Sans", "sans-serif"],
            "label": ["Public Sans", "sans-serif"]
        }
    },
  },
  plugins: [],
}
